# Tool pins track fluxcd/source-controller's choices.
LOCALBIN ?= $(shell pwd)/bin
CONTROLLER_GEN_VERSION ?= v0.21.0
KUSTOMIZE_VERSION ?= v5.7.1
ENVTEST_K8S_VERSION ?= 1.36.2

# Release coordinates. Override: make release IMG=ghcr.io/you/artifact-controller VERSION=v0.1.0
IMG ?= ghcr.io/kargops/artifact-controller
VERSION ?= v0.0.0-dev
PLATFORMS ?= linux/amd64,linux/arm64

CONTROLLER_GEN = $(LOCALBIN)/controller-gen
SETUP_ENVTEST = $(LOCALBIN)/setup-envtest
KUSTOMIZE = $(LOCALBIN)/kustomize

CHART_DIR ?= charts/artifact-controller

.PHONY: all
all: build

$(LOCALBIN):
	mkdir -p $(LOCALBIN)

.PHONY: controller-gen
controller-gen: $(LOCALBIN)
	@test -x $(CONTROLLER_GEN) || GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-tools/cmd/controller-gen@$(CONTROLLER_GEN_VERSION)

.PHONY: setup-envtest
setup-envtest: $(LOCALBIN)
	@test -x $(SETUP_ENVTEST) || GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest

.PHONY: kustomize
kustomize: $(LOCALBIN)
	@test -x $(KUSTOMIZE) || GOBIN=$(LOCALBIN) go install sigs.k8s.io/kustomize/kustomize/v5@$(KUSTOMIZE_VERSION)

.PHONY: generate
generate: controller-gen ## Generate deepcopy code.
	$(CONTROLLER_GEN) object paths="./..."

.PHONY: manifests
manifests: controller-gen ## Generate CRDs and RBAC, and sync them into the chart.
	$(CONTROLLER_GEN) rbac:roleName=artifact-controller-manager crd paths="./..." \
		output:crd:artifacts:config=config/crd/bases output:rbac:artifacts:config=config/rbac
	$(MAKE) chart-sync

# The chart cannot own these: they are controller-gen output. CRDs are synced
# into crd-base/ (a plain files dir, NOT Helm's special crds/) and emitted by
# templates/crds.yaml via .Files.Get, which returns raw bytes — necessary
# because CRD descriptions contain Go template syntax ({{ .SpecHash }}) that
# Helm would otherwise try to render. Emitting them as templated resources
# also means upgrades keep them current, which Helm's crds/ dir never does.
# Each synced CRD gets helm.sh/resource-policy: keep baked in: uninstall must
# never delete the CRDs, and with them every Artifact in the cluster.
.PHONY: chart-sync
chart-sync: ## Sync generated CRDs and the manager role into the Helm chart.
	mkdir -p $(CHART_DIR)/crd-base
	rm -f $(CHART_DIR)/crd-base/*.yaml
	for f in config/crd/bases/*.yaml; do \
		awk '1; /^  annotations:$$/ && !done { print "    helm.sh/resource-policy: keep"; done=1 }' \
			"$$f" > "$(CHART_DIR)/crd-base/$$(basename $$f)"; \
	done
	printf '%s\n' '# Generated by controller-gen from config/rbac/role.yaml — do not edit.' \
		'# Regenerate with: make manifests' > $(CHART_DIR)/templates/manager-clusterrole.yaml
	cat config/rbac/role.yaml >> $(CHART_DIR)/templates/manager-clusterrole.yaml

.PHONY: helm-lint
helm-lint: ## Lint and render the chart the way CI does.
	helm lint $(CHART_DIR)
	helm template test $(CHART_DIR) --dry-run -f $(CHART_DIR)/ci-values.yaml >/dev/null
	@echo "✅ chart lints and renders"

.PHONY: fmt
fmt:
	go fmt ./...

.PHONY: vet
vet:
	go vet ./...

.PHONY: build
build: generate fmt vet
	go build -o bin/artifact-controller ./cmd

.PHONY: test
test: generate manifests fmt vet setup-envtest ## Run all tests (downloads envtest binaries on first run).
	KUBEBUILDER_ASSETS="$$($(SETUP_ENVTEST) use $(ENVTEST_K8S_VERSION) --bin-dir $(LOCALBIN) -p path)" \
		go test ./... -count=1

.PHONY: run
run: generate manifests ## Run against the current kubeconfig context.
	go run ./cmd --zap-devel

.PHONY: install
install: manifests ## Install only the CRDs into the current cluster.
	kubectl apply -f config/crd/bases

##@ Release and deploy

.PHONY: docker-build
docker-build: ## Build the controller image for the local platform.
	docker build -t $(IMG):$(VERSION) .

.PHONY: docker-buildx
docker-buildx: ## Build and push a multi-arch image (requires a buildx builder).
	docker buildx build --push --platform=$(PLATFORMS) -t $(IMG):$(VERSION) .

.PHONY: release-manifest
release-manifest: manifests generate kustomize ## Render dist/install.yaml pinned to IMG:VERSION.
	mkdir -p dist
	cd config/default && $(KUSTOMIZE) edit set image ghcr.io/kargops/artifact-controller=$(IMG):$(VERSION)
	$(KUSTOMIZE) build config/default > dist/install.yaml
	@echo "wrote dist/install.yaml ($(IMG):$(VERSION))"

.PHONY: crds-manifest
crds-manifest: manifests kustomize ## Render dist/crds.yaml (CRDs only, for decoupled installs).
	mkdir -p dist
	$(KUSTOMIZE) build config/crd > dist/crds.yaml
	@echo "wrote dist/crds.yaml"

.PHONY: release
release: docker-buildx release-manifest crds-manifest ## Push the image and render the install bundles.
	@echo "Release $(VERSION) ready: push dist/install.yaml as a release asset."

.PHONY: deploy
deploy: release-manifest ## Apply the full install to the current cluster.
	kubectl apply --server-side -f dist/install.yaml

.PHONY: undeploy
undeploy: ## Remove the controller (CRDs included — deletes all Artifact objects).
	kubectl delete --ignore-not-found -f dist/install.yaml

# One-time after adding the repository on artifacthub.io (control panel →
# repositories → Add → kind "Helm charts", url oci://ghcr.io/kargops/charts/artifact-controller):
# grab the repository ID it assigns and run
#   make artifacthub-metadata AH_REPO_ID=<uuid>
# This pushes artifacthub-repo.yml under the special `artifacthub.io` tag,
# which links the listing to the repo and grants the verified-publisher badge.
# Requires oras (brew install oras) logged into ghcr.io.
.PHONY: artifacthub-metadata
artifacthub-metadata:
	@test -n "$(AH_REPO_ID)" || { echo "AH_REPO_ID is required"; exit 1; }
	mkdir -p dist
	sed 's/REPLACE_WITH_ARTIFACTHUB_REPOSITORY_ID/$(AH_REPO_ID)/' \
		$(CHART_DIR)/artifacthub-repo.yml > dist/artifacthub-repo.yml
	cd dist && oras push ghcr.io/kargops/charts/artifact-controller:artifacthub.io \
		--config /dev/null:application/vnd.cncf.artifacthub.config.v1+yaml \
		artifacthub-repo.yml:application/vnd.cncf.artifacthub.repository-metadata.layer.v1.yaml
