//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/fluxcd/pkg/apis/meta"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMIStoreSpec) DeepCopyInto(out *AMIStoreSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMIStoreSpec.
func (in *AMIStoreSpec) DeepCopy() *AMIStoreSpec {
	if in == nil {
		return nil
	}
	out := new(AMIStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Artifact) DeepCopyInto(out *Artifact) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Artifact.
func (in *Artifact) DeepCopy() *Artifact {
	if in == nil {
		return nil
	}
	out := new(Artifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Artifact) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactClass) DeepCopyInto(out *ArtifactClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactClass.
func (in *ArtifactClass) DeepCopy() *ArtifactClass {
	if in == nil {
		return nil
	}
	out := new(ArtifactClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtifactClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactClassList) DeepCopyInto(out *ArtifactClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArtifactClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactClassList.
func (in *ArtifactClassList) DeepCopy() *ArtifactClassList {
	if in == nil {
		return nil
	}
	out := new(ArtifactClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtifactClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactClassSpec) DeepCopyInto(out *ArtifactClassSpec) {
	*out = *in
	in.Store.DeepCopyInto(&out.Store)
	if in.Generator != nil {
		in, out := &in.Generator, &out.Generator
		*out = new(GeneratorSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Backoff != nil {
		in, out := &in.Backoff, &out.Backoff
		*out = new(BackoffSpec)
		**out = **in
	}
	if in.Drift != nil {
		in, out := &in.Drift, &out.Drift
		*out = new(DriftSpec)
		**out = **in
	}
	out.VerificationGracePeriod = in.VerificationGracePeriod
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactClassSpec.
func (in *ArtifactClassSpec) DeepCopy() *ArtifactClassSpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactList) DeepCopyInto(out *ArtifactList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Artifact, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactList.
func (in *ArtifactList) DeepCopy() *ArtifactList {
	if in == nil {
		return nil
	}
	out := new(ArtifactList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtifactList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactSpec) DeepCopyInto(out *ArtifactSpec) {
	*out = *in
	out.ClassRef = in.ClassRef
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Interval = in.Interval
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DeleteAfter != nil {
		in, out := &in.DeleteAfter, &out.DeleteAfter
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactSpec.
func (in *ArtifactSpec) DeepCopy() *ArtifactSpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactStatus) DeepCopyInto(out *ArtifactStatus) {
	*out = *in
	if in.LastFailureTime != nil {
		in, out := &in.LastFailureTime, &out.LastFailureTime
		*out = (*in).DeepCopy()
	}
	if in.GeneratorRef != nil {
		in, out := &in.GeneratorRef, &out.GeneratorRef
		*out = new(GeneratorReference)
		**out = **in
	}
	if in.GeneratorSucceededAt != nil {
		in, out := &in.GeneratorSucceededAt, &out.GeneratorSucceededAt
		*out = (*in).DeepCopy()
	}
	if in.LastVerifiedTime != nil {
		in, out := &in.LastVerifiedTime, &out.LastVerifiedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactStatus.
func (in *ArtifactStatus) DeepCopy() *ArtifactStatus {
	if in == nil {
		return nil
	}
	out := new(ArtifactStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackoffSpec) DeepCopyInto(out *BackoffSpec) {
	*out = *in
	out.InitialDelay = in.InitialDelay
	out.MaxDelay = in.MaxDelay
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackoffSpec.
func (in *BackoffSpec) DeepCopy() *BackoffSpec {
	if in == nil {
		return nil
	}
	out := new(BackoffSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftSpec) DeepCopyInto(out *DriftSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftSpec.
func (in *DriftSpec) DeepCopy() *DriftSpec {
	if in == nil {
		return nil
	}
	out := new(DriftSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeStoreSpec) DeepCopyInto(out *FakeStoreSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeStoreSpec.
func (in *FakeStoreSpec) DeepCopy() *FakeStoreSpec {
	if in == nil {
		return nil
	}
	out := new(FakeStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratorReference) DeepCopyInto(out *GeneratorReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratorReference.
func (in *GeneratorReference) DeepCopy() *GeneratorReference {
	if in == nil {
		return nil
	}
	out := new(GeneratorReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratorSpec) DeepCopyInto(out *GeneratorSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	if in.ProgressDeadline != nil {
		in, out := &in.ProgressDeadline, &out.ProgressDeadline
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratorSpec.
func (in *GeneratorSpec) DeepCopy() *GeneratorSpec {
	if in == nil {
		return nil
	}
	out := new(GeneratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPAuthSpec) DeepCopyInto(out *HTTPAuthSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(meta.LocalObjectReference)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPAuthSpec.
func (in *HTTPAuthSpec) DeepCopy() *HTTPAuthSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRequestSpec) DeepCopyInto(out *HTTPRequestSpec) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRequestSpec.
func (in *HTTPRequestSpec) DeepCopy() *HTTPRequestSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPStoreSpec) DeepCopyInto(out *HTTPStoreSpec) {
	*out = *in
	in.Observe.DeepCopyInto(&out.Observe)
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(HTTPRequestSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(HTTPAuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPStoreSpec.
func (in *HTTPStoreSpec) DeepCopy() *HTTPStoreSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIStoreSpec) DeepCopyInto(out *OCIStoreSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIStoreSpec.
func (in *OCIStoreSpec) DeepCopy() *OCIStoreSpec {
	if in == nil {
		return nil
	}
	out := new(OCIStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoManagerStoreSpec) DeepCopyInto(out *RepoManagerStoreSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(meta.LocalObjectReference)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoManagerStoreSpec.
func (in *RepoManagerStoreSpec) DeepCopy() *RepoManagerStoreSpec {
	if in == nil {
		return nil
	}
	out := new(RepoManagerStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3StoreSpec) DeepCopyInto(out *S3StoreSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3StoreSpec.
func (in *S3StoreSpec) DeepCopy() *S3StoreSpec {
	if in == nil {
		return nil
	}
	out := new(S3StoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreSpec) DeepCopyInto(out *StoreSpec) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3StoreSpec)
		**out = **in
	}
	if in.OCI != nil {
		in, out := &in.OCI, &out.OCI
		*out = new(OCIStoreSpec)
		**out = **in
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPStoreSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AMI != nil {
		in, out := &in.AMI, &out.AMI
		*out = new(AMIStoreSpec)
		**out = **in
	}
	if in.RepoManager != nil {
		in, out := &in.RepoManager, &out.RepoManager
		*out = new(RepoManagerStoreSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Fake != nil {
		in, out := &in.Fake, &out.Fake
		*out = new(FakeStoreSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreSpec.
func (in *StoreSpec) DeepCopy() *StoreSpec {
	if in == nil {
		return nil
	}
	out := new(StoreSpec)
	in.DeepCopyInto(out)
	return out
}
